### ISSUE TITLE
Hello there 

### ISSUE THREAD

**Issue by Reubencfernandes** [3ddelano/pc-statbot#1]
I see what you are up to

**Comment by 3ddelano** [comment]
Any suggestions, I will add Bluetooth devices soon which will show bluetooth headphone/speaker battery percentage since windows doesn't support it natively.

**Comment by 3ddelano** [comment]
Damn, windows doesn't have api for connecting to bluetooth battery. Android does though.

**Comment by SrIzan10** [comment]
And what about disk usage?

**Comment by 3ddelano** [comment]
Disk usage is there

**Comment by SrIzan10** [comment]
wdym?

**Comment by 3ddelano** [comment]
You can add any stat you want. The bot is made in a modular manner. You can even add storage usage of a certain folder, internet speed, etc as long as there is a way to get that value in NodeJS.
